<a href="https://colab.research.google.com/github/itsjoannalee/Github_lab/blob/main/%E8%B3%87%E6%96%99%E7%A7%91%E5%AD%B8%E5%AE%B6_%E7%AC%AC%E4%BA%8C%E5%A0%82%E4%BD%9C%E6%A5%AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

作業1

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import numpy as np
import pandas as pd

In [ ]:
cities={'city':['新竹','台中','桃園','苗栗','高雄','花蓮']}
cities_df=pd.DataFrame(cities)
print(cities_df)

  city
0   新竹
1   台中
2   桃園
3   苗栗
4   高雄
5   花蓮


作業2

In [ ]:
#team = np.zeros(4,dtype=int)
team = np.zeros(4,dtype=({'member':('name','number','team'),'formats':('U10','i2','U10')}))
print(team.dtype)
team['name']=['詹姆士','柯瑞','杜蘭特','德羅贊']
team['number']=[26,33,30,20]
team['team']=['湖人隊','勇士隊','籃網隊','馬刺隊']
print(team)


ValueError: ignored

作業3

In [ ]:
matrix_ten=np.full((5,5),10)
matrix_ten

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
matrix_ten[2][2]=0
matrix_ten

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10,  0, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

作業4

In [ ]:
x=np.random.rand(10,10)
x

array([[0.43418229, 0.1549611 , 0.51313925, 0.70705933, 0.82490716,
        0.1347847 , 0.57634113, 0.08185848, 0.31433031, 0.99251451],
       [0.825885  , 0.75393451, 0.38271113, 0.86297684, 0.53871193,
        0.98759423, 0.97995837, 0.54313178, 0.73400753, 0.49950406],
       [0.41814621, 0.15162322, 0.83445914, 0.83620039, 0.74199185,
        0.85763811, 0.217047  , 0.22796661, 0.20886505, 0.56153571],
       [0.84263116, 0.01967943, 0.73528107, 0.35095273, 0.02416174,
        0.90707048, 0.87915335, 0.69863051, 0.26814844, 0.78926347],
       [0.6434923 , 0.75146971, 0.5973481 , 0.8574929 , 0.02077159,
        0.89532728, 0.23570676, 0.16920454, 0.11557874, 0.22842791],
       [0.721628  , 0.79727494, 0.3510506 , 0.42672594, 0.3699255 ,
        0.91106559, 0.16048103, 0.53911729, 0.30929063, 0.6785384 ],
       [0.79165557, 0.39675816, 0.48916193, 0.48369987, 0.32821862,
        0.8527778 , 0.92919588, 0.42089572, 0.99501936, 0.78051013],
       [0.08099195, 0.89992538, 0.2243243

In [ ]:
print(x.max(),x.min())

0.9950193588945226 0.004819156644610412


作業5

In [ ]:
y=np.array([34,567,18,98,4,20,100])
y[y>50]

array([567,  98, 100])

作業6

In [ ]:
one_to_nine_array = np.array([np.full((1,9),1),np.full((1,9),2),np.full((1,9),3),np.full((1,9),4),
                np.full((1,9),5),np.full((1,9),6),np.full((1,9),7),np.full((1,9),8),np.full((1,9),9)])
m = np.array([1,2,3,4,5,6,7,8,9])
multiple = np.dot(one_to_nine_array,m)
multiple

array([[ 45],
       [ 90],
       [135],
       [180],
       [225],
       [270],
       [315],
       [360],
       [405]])

In [ ]:
multiple.sum()

2025

作業7

In [ ]:
tips_csv = pd.read_csv("/content/drive/MyDrive/python/tips - tips.csv",encoding="utf-8")
tips_csv.head(15)

total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
1        10.34  1.66    Male     No  Sun  Dinner     3
2        21.01  3.50    Male     No  Sun  Dinner     3
3        23.68  3.31    Male     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
5        25.29  4.71    Male     No  Sun  Dinner     4
6         8.77  2.00    Male     No  Sun  Dinner     2
7        26.88  3.12    Male     No  Sun  Dinner     4
8        15.04  1.96    Male     No  Sun  Dinner     2
9        14.78  3.23    Male     No  Sun  Dinner     2
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2

In [ ]:
tips_csv.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

作業8

In [ ]:
print('平均值',tips_csv['total_bill'].mean())
print('加總',tips_csv['total_bill'].sum())
print('最大值',tips_csv['total_bill'].max())
print('最小值',tips_csv['total_bill'].min())

平均值 19.78594262295082
加總 4827.77
最大值 50.81
最小值 3.07


作業9

In [ ]:
member_inedx = pd.Index(['PG','SG','SF','PF','C'])
#print(member_inedx)
member_number=np.array([9, 23, 33, 91, 13])
member_players=np.array(['Ron Harper','Michael Jordan','Scottie Pippen','Dennis Rodman','Luc Longley'])
#print(member_number),print(member_players)
member_number_series=pd.Series(member_number,index=member_inedx)
member_players_series=pd.Series(member_players,index=member_inedx)
#print(member_number_series,member_players_series)
member=pd.DataFrame()
member['number']=member_number_series
member['player']=member_players_series
print(member)

    number          player
PG       9      Ron Harper
SG      23  Michael Jordan
SF      33  Scottie Pippen
PF      91   Dennis Rodman
C       13     Luc Longley


作業10

In [ ]:
data={'grammer':['Python','C','Java','GO',np.nan,'SQL','PHP','Python'],
   'score':[1,2,np.nan,4,5,6,7,10]} 
data_df=pd.DataFrame(data)
print(data_df)

  grammer  score
0  Python    1.0
1       C    2.0
2    Java    NaN
3      GO    4.0
4     NaN    5.0
5     SQL    6.0
6     PHP    7.0
7  Python   10.0


In [ ]:
data_df_withoutNaN=data_df[data_df['grammer'].notna()] #將grammer有na值的列刪除
data_df_withoutNaN
print(data_df_withoutNaN['grammer'].value_counts())

Python    2
C         1
Java      1
GO        1
SQL       1
PHP       1
Name: grammer, dtype: int64


作業11

In [ ]:
data={'grammer':['Python','C','Java','GO',np.nan,'SQL','PHP','Python'],
   'score':[1,2,np.nan,4,5,6,7,10]}
data_df=pd.DataFrame(data)
data_df

grammer  score
0  Python    1.0
1       C    2.0
2    Java    NaN
3      GO    4.0
4     NaN    5.0
5     SQL    6.0
6     PHP    7.0
7  Python   10.0

In [ ]:
data_df[data_df['score']>3]

grammer  score
3      GO    4.0
4     NaN    5.0
5     SQL    6.0
6     PHP    7.0
7  Python   10.0

作業12

In [4]:
data={'grammer':['Python','C','Java','GO','SQL','PHP','Python'],
   'score':[1,2,np.nan,4,6,7,10]}
data_df=pd.DataFrame(data)
data_df

grammer  score
0  Python    1.0
1       C    2.0
2    Java    NaN
3      GO    4.0
4     SQL    6.0
5     PHP    7.0
6  Python   10.0

In [5]:
data_df[(data_df['score']>3) & (data_df['score']<7)]

grammer  score
3      GO    4.0
4     SQL    6.0

作業13

In [6]:
data={'grammer':['Python','C','Java','GO','SQL','PHP','Python'],
   'score':[1,2,np.nan,4,6,7,10]}
data_df=pd.DataFrame(data)
data_df

grammer  score
0  Python    1.0
1       C    2.0
2    Java    NaN
3      GO    4.0
4     SQL    6.0
5     PHP    7.0
6  Python   10.0

In [11]:
data_df.loc[7]=['Perl',6.6]
print(data_df)

  grammer  score
0  Python    1.0
1       C    2.0
2    Java    NaN
3      GO    4.0
4     SQL    6.0
5     PHP    7.0
6  Python   10.0
7    Perl    6.6


作業14

In [15]:
Z1 = np.arange(0,20)
Z2 = np.arange(10,30)
print(np.intersect1d(Z1,Z2))

[10 11 12 13 14 15 16 17 18 19]


作業15

In [25]:
arr = np.array( [ 0, 18, 45, 33, 24, 55, 46, 72, 98, 29 ] )
arr[(arr%2)==1]= -1
arr

array([ 0, 18, -1, -1, 24, -1, 46, 72, 98, -1])